changed: Improve sanity checking for some variables changed: Logic to determine USR_SHARE_PATH

diff --git a/bin/arno-iptables-firewall b/bin/arno-iptables-firewall
--- a/bin/arno-iptables-firewall
+++ b/bin/arno-iptables-firewall
@@ -258,7 +258,7 @@ config_check()
 
   # Check whether we know the plugin binary path
   ##############################################
-  if [ ! -d "$PLUGIN_BIN_PATH" ]; then
+  if [ -z "$PLUGIN_BIN_PATH" -o ! -d "$PLUGIN_BIN_PATH" ]; then
     printf "\033[40m\033[1;31mERROR: The PLUGIN_BIN_PATH ($PLUGIN_BIN_PATH) does not exist!\033[0m\n" >&2
     printf "\033[40m\033[1;31m       Please check your installation and/or configuration file.\033[0m\n\n" >&2
     retval=1
@@ -266,7 +266,7 @@ config_check()
 
   # Check whether we know the plugin config path
   ##############################################
-  if [ ! -d "$PLUGIN_CONF_PATH" ]; then
+  if [ -z "$PLUGIN_CONF_PATH" -o ! -d "$PLUGIN_CONF_PATH" ]; then
     printf "\033[40m\033[1;31mERROR: The PLUGIN_CONF_PATH ($PLUGIN_CONF_PATH) does not exist!\033[0m\n" >&2
     printf "\033[40m\033[1;31m       Please check your installation and/or configuration file.\033[0m\n\n" >&2
     retval=1
@@ -4945,7 +4945,7 @@ job_remove()
 {
   local SCRIPT_NAME="$1"
 
-  if [ -f "$JOBS_FILE" ]; then
+  if [ -n "$JOBS_FILE" -a -f "$JOBS_FILE" ]; then
     echo "${INDENT}Removing background job \"$SCRIPT_NAME\""
 
     # Remove job from jobs file
@@ -4963,6 +4963,11 @@ job_remove()
 job_add()
 {
   local SCRIPT_NAME SCRIPT_TIME SCRIPT_PATH
+
+  if [ -z "$JOBS_FILE" ]; then
+    echo "** ERROR: Unable to add job since JOBS_FILE is not defined" >&2
+    return 1
+  fi
 
   SCRIPT_NAME="$1"
   shift
@@ -4991,6 +4996,11 @@ job_run_once()
 {
   local SCRIPT_NAME="$1"
 
+  if [ -z "$JOB_EXECUTER" ]; then
+    echo "** ERROR: Unable to execute job \"$SCRIPT_NAME\" since JOB_EXECUTER is not defined" >&2
+    return 1
+  fi
+
   echo "${INDENT}Foreground running job helper script \"$SCRIPT_NAME\""
 
   # Source script
@@ -5005,6 +5015,10 @@ job_run_once()
 # Check if job process is running
 job_process_is_running()
 {
+  if [ -z "$JOB_PROCESSOR" ]; then
+    return 1
+  fi
+
   if ! pgrep -f "$JOB_PROCESSOR" >/dev/null 2>&1; then
     return 1
   fi
@@ -5056,6 +5070,11 @@ jobs_process_terminate_check()
 jobs_process_start()
 {
   if [ -n "$JOBS_FILE" -a -e "$JOBS_FILE" ]; then
+    if [ -z "$JOB_PROCESSOR" ]; then
+      echo "** ERROR: Unable to start jobs processor since JOB_PROCESSOR is not defined" >&2
+      return
+    fi
+
     echo "Starting background jobs processor"
 
     # Run script for background process
@@ -5080,7 +5099,7 @@ jobs_process_start()
 # Stop jobs processor
 jobs_process_stop()
 {
-  if [ -n "$JOBS_FILE" -a -e "$JOBS_FILE" ]; then
+  if [ -n "$JOBS_LOCK_NAME" -a -n "$JOBS_FILE" -a -e "$JOBS_FILE" ]; then
     echo "Stopping background jobs processor"
 
     # Enter critical section (ignore whether we actually can obtain the lock)
diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -2095,22 +2095,23 @@ ICMPV6_MLD_TYPES="130 131 132 143"
 ######################################################################
 NF_CONNTRACK_STATE="-m conntrack --ctstate"
 
-# Check plugin bin path and fallback in case it's empty
-#######################################################
-if [ -z "$PLUGIN_BIN_PATH" ]; then
-  if [ -d "/usr/local/share/arno-iptables-firewall/plugins" ]; then
-    PLUGIN_BIN_PATH="/usr/local/share/arno-iptables-firewall/plugins"
-  elif [ -d "/usr/share/arno-iptables-firewall/plugins" ]; then
-    PLUGIN_BIN_PATH="/usr/share/arno-iptables-firewall/plugins"
-  fi
-fi
-
 # Set system wide share path
 ############################
 if [ -z "$USR_SHARE_PATH" ]; then
-  # FIXME: For now we simply retrieve the path from what is specified for
-  #        our plugin path. Perhaps there's a smarter way?
-  USR_SHARE_PATH="$(dirname "$PLUGIN_BIN_PATH")"
+  USR_SHARE_PATH="/usr/local/share/arno-iptables-firewall"
+  if [ ! -d "$USR_SHARE_PATH" ]; then
+    USR_SHARE_PATH="/usr/share/arno-iptables-firewall"
+    if [ ! -d "$USR_SHARE_PATH" ]; then
+      USE_SHARE_PATH=""
+      echo "** ERROR: Unable to determine USR_SHARE_PATH!" >&2
+    fi
+  fi
+fi
+
+# Check plugin bin path and fallback in case it's empty
+#######################################################
+if [ -z "$PLUGIN_BIN_PATH" ]; then
+  PLUGIN_BIN_PATH="${USR_SHARE_PATH/plugins"
 fi
 
 # File containing (background) jobs to run
