changed: Moved simple default policy block for IPv4/IPv6 to a more logical location
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/trunk@299 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/bin/arno-iptables-firewall b/bin/arno-iptables-firewall
--- a/bin/arno-iptables-firewall
+++ b/bin/arno-iptables-firewall
@@ -752,6 +752,41 @@ setup_default_policies()
     iptables -P OUTPUT ACCEPT
   fi
 
+  # When IPv4 support is active, disable IPv6 traffic
+  if [ "$IPV6_SUPPORT" = "1" ]; then
+    echo "NOTE: IPv6 mode selected, setting simple default policy for IPv4"
+    ip4tables -P INPUT DROP
+    ip4tables -P FORWARD DROP
+    ip4tables -P OUTPUT ACCEPT
+    
+    ip4tables -A INPUT -i lo -j ACCEPT
+    ip4tables -A FORWARD -i lo -j ACCEPT
+
+    IFS=' ,'
+    for interface in $INT_IF $TRUSTED_IF; do
+      ip4tables -A INPUT -i $interface -j ACCEPT
+    done
+  elif [ "$IPV6_DETECTED" = "1" ]; then
+    # IPv6 support available on the system?
+    if [ -x "$IP6TABLES" ]; then
+      echo "NOTE: IPv4 mode selected, setting simple default policy for IPv6"
+      ip6tables -P INPUT DROP
+      ip6tables -P FORWARD DROP
+      ip6tables -P OUTPUT ACCEPT
+
+      ip6tables -A INPUT -i lo -j ACCEPT
+      ip6tables -A FORWARD -i lo -j ACCEPT
+
+      IFS=' ,'
+      for interface in $INT_IF $TRUSTED_IF; do
+        ip6tables -A INPUT -i $interface -j ACCEPT
+      done
+    else
+      printf "\033[40m\033[1;31mWARNING: IPv4 support enabled, but unable to set the default policy\033[0m\n" >&2
+      printf "\033[40m\033[1;31m         for IPv6 to DROP as the ip6tables-binary is not available!\033[0m\n" >&2
+    fi
+  fi
+
   # The POST_INPUT_DROP_CHAIN should temporarily DROP for now
   # We'll change this once the rules are in place
   ###########################################################
@@ -4392,41 +4427,6 @@ setup_firewall_rules()
 
   echo "Setting up firewall rules:"
   echo "-------------------------------------------------------------------------------"
-
-  # When IPv4 support is active, disable IPv6 traffic
-  if [ "$IPV6_SUPPORT" = "1" ]; then
-    echo "NOTE: IPv6 mode selected, setting simple default policy for IPv4"
-    ip4tables -P INPUT DROP
-    ip4tables -P FORWARD DROP
-    ip4tables -P OUTPUT ACCEPT
-    
-    ip4tables -A INPUT -i lo -j ACCEPT
-    ip4tables -A FORWARD -i lo -j ACCEPT
-
-    IFS=' ,'
-    for interface in $INT_IF $TRUSTED_IF; do
-      ip4tables -A INPUT -i $interface -j ACCEPT
-    done
-  elif [ "$IPV6_DETECTED" = "1" ]; then
-    # IPv6 support available on the system?
-    if [ -x "$IP6TABLES" ]; then
-      echo "NOTE: IPv4 mode selected, setting simple default policy for IPv6"
-      ip6tables -P INPUT DROP
-      ip6tables -P FORWARD DROP
-      ip6tables -P OUTPUT ACCEPT
-
-      ip6tables -A INPUT -i lo -j ACCEPT
-      ip6tables -A FORWARD -i lo -j ACCEPT
-
-      IFS=' ,'
-      for interface in $INT_IF $TRUSTED_IF; do
-        ip6tables -A INPUT -i $interface -j ACCEPT
-      done
-    else
-      printf "\033[40m\033[1;31mWARNING: IPv4 support enabled, but unable to set the default policy\033[0m\n" >&2
-      printf "\033[40m\033[1;31m         for IPv6 to DROP as the ip6tables-binary is not available!\033[0m\n" >&2
-    fi
-  fi
 
   # Setup all TCP MSS stuff
   #########################
