changed: Report amount of failed firewall rules

diff --git a/bin/arno-iptables-firewall b/bin/arno-iptables-firewall
--- a/bin/arno-iptables-firewall
+++ b/bin/arno-iptables-firewall
@@ -5343,10 +5343,10 @@ show_applied()
   echo ""
   DATE=`LC_ALL=C date +'%b %d %H:%M:%S'`
 
-  if [ "$RULE_WARNING" = "1" ]; then
-    printf "$DATE \033[40m\033[1;31mWARNING: Not all firewall rules are applied.\033[0m\n" >&2
-    echo "$DATE ** WARNING: Not all firewall rules are applied **" >> $FIREWALL_LOG
-    echo "** WARNING: Not all firewall rules are applied **" |logger -t firewall -p kern.info
+  if [ "$RULE_WARNING" != "0" ]; then
+    printf "$DATE \033[40m\033[1;31mWARNING: $RULE_WARNING firewall rules failed to apply!\n\033[0m" >&2
+    echo "$DATE ** WARNING: $RULE_WARNING firewall rules failed to apply **" >> $FIREWALL_LOG
+    echo "** WARNING: $RULE_WARNING firewall rules failed to apply **" |logger -t firewall -p kern.info
   else
     printf "$DATE \033[40m\033[1;32mAll firewall rules applied.\033[0m\n"
     echo "$DATE ** All firewall rules applied **" >> $FIREWALL_LOG
