fixed: Cosmetics in the init script
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/trunk@224 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/etc/init.d/arno-iptables-firewall b/etc/init.d/arno-iptables-firewall
--- a/etc/init.d/arno-iptables-firewall
+++ b/etc/init.d/arno-iptables-firewall
@@ -59,17 +59,15 @@ if [ "$VERBOSE" = "0" ]; then
 
   # Call firewall script:
   result=`$PROGRAM $*`
-  return_val=$?
+  retval=$?
 
-  if [ "$return_val" = "0" ]; then
-    echo "done."
-  else
-    echo "FAILED!"
+  if [ "$retval" != "0" ]; then
+    echo "FAILED!" >&2
   fi
 else
   $PROGRAM $*
-  return_val=$?
+  retval=$?
 fi
 
 # Return value:
-exit $return_val
+exit $retval
