changed: Improve logging in aif-job-processor

diff --git a/share/arno-iptables-firewall/aif-job-processor b/share/arno-iptables-firewall/aif-job-processor
--- a/share/arno-iptables-firewall/aif-job-processor
+++ b/share/arno-iptables-firewall/aif-job-processor
@@ -89,7 +89,7 @@ job_process()
     # Enter critical section:
     if ! lock_enter "$JOBS_LOCK_NAME"; then
       # Lock failed, just keeping trying forever since there's no point in exiting here
-      [ $VERBOSE -eq 1 ] && echo "Lock failed, (re)trying next loop..." >&2
+      [ $VERBOSE -eq 1 ] && echo "Lock failed, (re)trying next loop..."
       continue
     fi
 
@@ -128,13 +128,10 @@ job_process()
           # Release extra FD
           exec 3>&-
 
-          if [ $VERBOSE -eq 1 ]; then
-            echo "$err_result" >&2
-          fi
-
           # In case an error occurred, log it
-          if [ $retval -ne 0 ]; then
-            echo "${err_result}" |sed s/"^"/"AIF-${SCRIPT_NAME}: "/g |logger -t firewall -p kern.info
+          if [ $retval -ne 0 -o -n "$err_result" ]; then
+            echo "$err_result" >&2
+            echo "$err_result" |sed s/"^"/"AIF-${SCRIPT_NAME}: "/g |logger -t firewall -p kern.info
           fi
 
           # Reset counter
