changed: Get rid of DNS_FAIL_LOG_REPEAT setting

diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -1352,8 +1352,8 @@ get_dynamic_host_cached()
   local host="$1"
   local retval=0
   local cache_lookup=""
-  local cache_time=0 fail_count=0 log_count=0
-  local age max_age cur_time store_ip threshold log_repeat count
+  local cache_time=0 fail_count=0
+  local age max_age cur_time store_ip threshold count
 
   # Don't try to resolve stuff that's already numeric
   if is_numeric_ip "$host"; then
@@ -1405,11 +1405,6 @@ get_dynamic_host_cached()
         fail_count=$count
       fi
 
-      count="$(echo "$cache_lookup" |cut -s -d' ' -f5)"
-      if [ -n "$count" ]; then
-        log_count=$count
-      fi
-
       # Try to get from (old) cache, if allowed
       if [ "$DNS_FAIL_THRESHOLD" != "0" ]; then
         host_ip="$(echo "$cache_lookup" |cut -s -d' ' -f2)"
@@ -1417,32 +1412,16 @@ get_dynamic_host_cached()
     fi
 
 
-    log_count=$((log_count + 1))
-
     if [ -z "$host_ip" -o "$host_ip" = "NO_IP" ]; then
       host_ip=""
       printf "\033[40m\033[1;31mFAILED!\n\033[0m"
-      if [ $log_count -eq 1 ]; then
-        echo "** ERROR: Unresolvable host \"$host\" and no old IP to fallback on! **" >&2
-      fi
+      echo "** ERROR: Unresolvable host \"$host\" and no old IP to fallback on! **" >&2
     else
       echo "$host_ip (cached!)"
-      if [ $log_count -eq 1 ]; then
-        echo "** WARNING($retval): Unresolvable host \"$host\". Re-using old IP ($host_ip)! **" >&2
-      fi
+      echo "** WARNING($retval): Unresolvable host \"$host\". Re-using old IP ($host_ip)! **" >&2
+
       # Ignore error:
       retval=0
-    fi
-
-
-    if [ -n "$DNS_FAIL_LOG_REPEAT" ]; then
-      log_repeat=$DNS_FAIL_LOG_REPEAT
-    else
-      log_repeat=0 # default
-    fi
-
-    if [ $log_count -gt $log_repeat ]; then
-      log_count=0
     fi
 
     if [ -n "$DNS_FAIL_THRESHOLD" ]; then
@@ -1473,10 +1452,10 @@ get_dynamic_host_cached()
 
   if [ -n "$cache_lookup" ]; then
     # Update existing entry
-    sed -i s/"^$host[[:blank:]].*"/"$host $store_ip $cache_time $fail_count $log_count"/ "${HOST_CACHE_FILE}"
+    sed -i s/"^$host[[:blank:]].*"/"$host $store_ip $cache_time $fail_count"/ "${HOST_CACHE_FILE}"
   else
     # Add new entry
-    echo "$host $store_ip $(($(date +'%s') / 60)) 1 1" >>"${HOST_CACHE_FILE}"
+    echo "$host $store_ip $(($(date +'%s') / 60)) $fail_count" >>"${HOST_CACHE_FILE}"
   fi
 
   return $retval
