Changed: Error text
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/branches/1.9-dev@40 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -432,7 +432,7 @@ sysctl_multi()
       return 0
     fi
   done
-  printf "\033[40m\033[1;31mKernel variables $VARIABLES ALL FAILED to set! This may be a problem!\033[0m\n" >&2
+  printf "\033[40m\033[1;31mKernel variable(s) \"$VARIABLES"\" FAILED to set! This may be a problem!\033[0m\n" >&2
   return 1
 }
 
