changed: Better check whether all required commands are available + cosmetics
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/trunk@195 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -58,7 +58,7 @@ find_command()
   if [ -x "$1" ]; then
     echo "$1"
   else
-    echo "$(which $(basename "$1") 2>/dev/null)"
+    which $(basename "$1") 2>/dev/null
   fi
 }
 
@@ -68,31 +68,35 @@ check_command()
 {
   local path
 
-  case "$1" in
-    /*) path="" ;;
-    ip|tc|modprobe|sysctl) path="/sbin/" ;;
-    sed|cat|date|uname) path="/bin/" ;;
-    *) path="/usr/bin/" ;;
-  esac
+  IFS=' '
+  for cmd in $*; do
+    case "$cmd" in
+      /*) path="" ;;
+      ip|tc|modprobe|sysctl) path="/sbin/" ;;
+      sed|cat|date|uname) path="/bin/" ;;
+      *) path="/usr/bin/" ;;
+    esac
 
-  if [ -x "$path$1" ]; then
-    return 0
-  fi
+    if [ -x "$path$cmd" ]; then
+      return 0
+    fi
 
-  if which "$1" >/dev/null 2>&1; then
-    return 0
-  else
-    return 1
-  fi
+    if which "$cmd" >/dev/null 2>&1; then
+      return 0
+    fi
+  done
+  
+  return 1
 }
 
 
 # Check whether a binary is available and if not, generate an error and stop program execution
 check_command_error()
 {
-  if ! check_command "$1"; then
-    printf "\033[40m\033[1;31mERROR: Binary \"$1\" does not exist or is not executable!\033[0m\n" >&2
-    printf "\033[40m\033[1;31m       Please investigate. Quitting...\033[0m\n" >&2
+  if ! check_command "$@"; then
+    printf "\033[40m\033[1;31mERROR  : Command(s) \"$(echo "$@" |tr ' ' '|')\" is/are not available!\033[0m\n" >&2
+    printf "\033[40m\033[1;31m         Please investigate. Quitting...\033[0m\n" >&2
+    echo ""
     exit 2
   fi
 }
@@ -101,12 +105,13 @@ check_command_error()
 # Check whether a binary is available and if not, generate a warning but continue program execution
 check_command_warning()
 {
-  check_command "$1"
+  check_command "$@"
   local retval=$?
 
   if [ "$retval" != "0" ]; then
-    printf "\033[40m\033[1;31mWARNING: Binary \"$1\" does not exist or is not executable!\033[0m\n" >&2
+    printf "\033[40m\033[1;31mWARNING: Command(s) \"$(echo "$@" |tr ' ' '|')\" is/are not available!\033[0m\n" >&2
     printf "\033[40m\033[1;31m         Please investigate. This *may* be a problem!\033[0m\n" >&2
+    echo ""
   fi
 
   return $retval
@@ -116,7 +121,7 @@ check_command_warning()
 check_binary()
 {
   printf "\033[40m\033[1;31mWARNING: Function check_binary() will soon be deprecated, please use check_command_error() instead!\033[0m\n" >&2
-  check_command_error "$1"
+  check_command_error "$@"
 }
 
 
