changed: More cosmetics in sysctl_multi()
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/trunk@134 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -340,9 +340,6 @@ sysctl_multi()
 
   VARIABLES="$@"
   
-  local retval
-  local result
-
   IFS=' '
   for variable in $VARIABLES; do
     if $SYSCTL $(echo "$variable" |cut -d'=' -f1) >/dev/null 2>&1; then
@@ -357,7 +354,7 @@ sysctl_multi()
       fi
     fi
   done
-  printf "\033[40m\033[1;31m${INDENT}ERROR: ($retval) Unable to set kernel variable(s) \"$(echo "$VARIABLES" |tr ' ' '|')\". This may be a problem!\033[0m\n" >&2
+  printf "\033[40m\033[1;31m${INDENT}ERROR: Unable to find kernel parameters \"$(echo "$VARIABLES" |tr ' ' '|')\"!\033[0m\n" >&2
   return 1
 }
 
