changed: Move locking to environment + implement lock-name argument for lock functions

diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -1485,6 +1485,80 @@ get_dynamic_host_cached()
 }
 
 
+lock_leave()
+{
+  local LOCK_FILE
+
+  if [ -z "$1" ]; then
+    echo "ERROR: Exception due to missing lock argument" >&2
+    return 1 # Failure
+  fi
+
+  LOCK_FILE="/var/lock/aif_$1.lock"
+
+  # Remove lockfile
+  rm -f "$LOCK_FILE"
+
+  # Disable int handler
+  trap - INT TERM EXIT
+}
+
+
+lock_ctrl_handler()
+{
+  lock_leave "$1"
+
+  stty intr ^C # Back to normal
+  exit         # Yep, I meant to do that... Kill/hang the shell.
+}
+
+
+# Use lock_enter() to prevent running of multiple instances
+lock_enter()
+{
+  local LOCK_FILE
+
+  if [ -z "$1" ]; then
+    echo "ERROR: Exception due to missing lock argument" >&2
+    return 1 # Failure
+  fi
+
+  LOCK_FILE="/var/lock/aif_$1.lock"
+
+  local FAIL_COUNT=0
+
+  while [ $FAIL_COUNT -lt 2 ]; do
+    if ( set -o noclobber; echo "$$" > "$LOCK_FILE") 2> /dev/null; then
+      # Setup int handler
+      trap "lock_ctrl_handler $LOCK_FILE" INT TERM EXIT
+
+      return 0 # Lock success
+    fi
+
+    # lock failed, check if the process is dead
+    local PID="$(cat "${LOCK_FILE}")"
+
+    # if cat isn't able to read the file, another instance is probably
+    # about to remove the lock -- exit, we're *still* locked
+    # Thanks to Grzegorz Wierzowiecki for pointing out this race condition on
+    # http://wiki.grzegorz.wierzowiecki.pl/code:mutex-in-bash
+    if [ $? -eq 0 ]; then
+      if ! kill -0 "$PID" 2>/dev/null; then
+        # lock is stale, remove it and restart
+        echo "WARNING: Removing stale lock of nonexistant PID ${PID}" >&2
+        rm -f "$LOCK_FILE"
+      fi
+    fi
+
+    FAIL_COUNT=$((FAIL_COUNT + 1))
+  done
+
+  echo "ERROR: Failed to acquire lockfile: $LOCK_FILE. Held by PID $(cat $LOCK_FILE)" >&2
+
+  return 1 # Lock failed
+}
+
+
 # Helper function to show interfaces / ips in front of verbose line
 # $1 =  interfaces. $2 = ips
 show_if_ip()
