changed: printf/echo doesn't like $@, use $* instead + cosmetics
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/trunk@511 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -291,7 +291,7 @@ ip4tables()
 
   if [ $retval -ne 0 ]; then
     # Show any (error) messages in red
-    printf "\033[40m\033[1;31m$IP4TABLES $@\nERROR ($retval): $result\033[0m\n" >&2
+    printf "\033[40m\033[1;31m${IP4TABLES} $*\nERROR ($retval): ${result}\033[0m\n" >&2
     if note_iptables_error "$@"; then
       IPTABLES_ERROR=1
     fi
@@ -312,7 +312,7 @@ ip6tables()
 
   if [ $retval -ne 0 ]; then
     # Show any (error) messages in red
-    printf "\033[40m\033[1;31m$IP6TABLES $@\nERROR ($retval): $result\033[0m\n" >&2
+    printf "\033[40m\033[1;31m${IP6TABLES} $*\nERROR ($retval): ${result}\033[0m\n" >&2
     if note_iptables_error "$@"; then
       IPTABLES_ERROR=1
     fi
@@ -333,7 +333,7 @@ ip4tables_save()
 
   if [ $retval -ne 0 ]; then
     # Show any (error) messages in red
-    printf "\033[40m\033[1;31m$IP4TABLES_SAVE $@\nERROR ($retval) \033[0m\n" >&2
+    printf "\033[40m\033[1;31m${IP4TABLES_SAVE} $*\nERROR ($retval)\033[0m\n" >&2
     IPTABLES_ERROR=1
   fi
 
@@ -350,7 +350,7 @@ ip4tables_restore()
 
   if [ $retval -ne 0 ]; then
     # Show any (error) messages in red
-    printf "\033[40m\033[1;31m$IP4TABLES_RESTORE $@\nERROR ($retval): $result\033[0m\n" >&2
+    printf "\033[40m\033[1;31m${IP4TABLES_RESTORE} $*\nERROR ($retval): ${result}\033[0m\n" >&2
     IPTABLES_ERROR=1
   elif [ -n "$result" ]; then
     echo "${INDENT}$result"
@@ -369,7 +369,7 @@ ip6tables_save()
 
   if [ $retval -ne 0 ]; then
     # Show any (error) messages in red
-    printf "\033[40m\033[1;31m$IP6TABLES_SAVE $@\nERROR ($retval)\033[0m\n" >&2
+    printf "\033[40m\033[1;31m${IP6TABLES_SAVE} $*\nERROR ($retval)\033[0m\n" >&2
     IPTABLES_ERROR=1
   fi
 
@@ -386,7 +386,7 @@ ip6tables_restore()
 
   if [ $retval -ne 0 ]; then
     # Show any (error) messages in red
-    printf "\033[40m\033[1;31m$IP6TABLES_RESTORE $@\nERROR ($retval): $result\033[0m\n" >&2
+    printf "\033[40m\033[1;31m${IP6TABLES_RESTORE} $*\nERROR ($retval): ${result}\033[0m\n" >&2
     IPTABLES_ERROR=1
   elif [ -n "$result" ]; then
     echo "${INDENT}$result"
@@ -413,15 +413,15 @@ modprobe()
     if [ $retval -ne 0 ]; then
       if ! echo "$result" |grep -q -e "Module .* not found" -e "Can't locate module"; then
         # Show any (error) messages in red
-        printf "\033[40m\033[1;31m${MODPROBE} $@\nERROR ($retval): $result\033[0m\n" >&2
+        printf "\033[40m\033[1;31m${MODPROBE} $*\nERROR ($retval): ${result}\033[0m\n" >&2
       elif [ "$COMPILED_IN_KERNEL_MESSAGES" != "0" ]; then
-        printf "\033[40m\033[1;31m${MODPROBE} $@\nWARNING ($retval): $result. Assuming compiled-in-kernel!\033[0m\n" >&2
+        printf "\033[40m\033[1;31m${MODPROBE} $*\nWARNING ($retval): $result. Assuming compiled-in-kernel!\033[0m\n" >&2
       fi
       return $retval
     else
       if echo "$result" |grep -q -e '^WARNING:'; then
         # Show any (warning) messages in red
-        printf "\033[40m\033[1;31m${MODPROBE} $@\nWARNING: $result\033[0m\n" >&2
+        printf "\033[40m\033[1;31m${MODPROBE} $*\nWARNING: ${result}\033[0m\n" >&2
       else
         echo "${INDENT}Loaded kernel module $1. $result"
       fi
@@ -514,7 +514,7 @@ sysctl()
 
   if [ $retval -ne 0 ]; then
     # Show any (error) messages in red
-    printf "\033[40m\033[1;31m$SYSCTL $@\nERROR ($retval): $result\033[0m\n" >&2
+    printf "\033[40m\033[1;31m${SYSCTL} $*\nERROR ($retval): ${result}\033[0m\n" >&2
     return $retval
   fi
   
