fixed: modprobe_multi() for older versions of modprobe (like we did with the modprobe() function too)
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/trunk@265 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -283,7 +283,7 @@ modprobe()
     retval=$?
 
     if [ "$retval" != "0" ]; then
-      if ! echo "$result" |grep -q -e 'Module .* not found' -e "Can't locate module"; then
+      if ! echo "$result" |grep -q -e "Module .* not found" -e "Can't locate module"; then
         # Show any (error) messages in red
         printf "\033[40m\033[1;31m${MODPROBE} $@: ($retval) $result\033[0m\n" >&2
       elif [ "$COMPILED_IN_KERNEL_MESSAGES" != "0" ]; then
@@ -342,7 +342,7 @@ modprobe_multi()
       retval=$?
 
       if [ "$retval" != "0" ]; then
-        if ! echo "$result" |grep -q -e '^FATAL: Module .* not found'; then
+        if ! echo "$result" |grep -q -e "Module .* not found" -e "Can't locate module"; then
           # Show any (error) messages in red
           printf "\033[40m\033[1;31m${modprobe_commandline}: ($retval) $result\033[0m\n" >&2
         fi
