fixed: modprobe_multi() needs the same fix as modprobe() (follow up for r654)
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/trunk@655 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/environment b/share/arno-iptables-firewall/environment
--- a/share/arno-iptables-firewall/environment
+++ b/share/arno-iptables-firewall/environment
@@ -503,7 +503,7 @@ modprobe_multi()
         retval=$?
 
         if [ $retval -ne 0 ]; then
-          if ! echo "$result" |grep -q -e "Module .* not found" -e "Can't locate module"; then
+          if ! echo "$result" |grep -q -e "Module .* not found" -e "Can't locate module" -e "^ *$"; then
             # Show any (error) messages in red
             printf "\033[40m\033[1;31m${modprobe_commandline}\nERROR ($retval): $result\033[0m\n" >&2
           fi
