changed: When resolving a hostname fails, flag as a (plugin) error

diff --git a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
--- a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
+++ b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
@@ -2,6 +2,10 @@
 ###############################
 PLUGIN_CONF_FILE="dyndns-host-open.conf"
 
+# Preinit return value for success
+PLUGIN_RET_VAL=0
+
+
 # Check sanity of environment
 dyndns_host_open_helper_sanity_check()
 {
@@ -29,6 +33,8 @@ dyndns_host_open_helper_sanity_check()
 
 dyndns_host_open_helper_setup_rules()
 {
+  local RETVAL=0
+
   # Flush the DYNDNS_CHAIN
   iptables -F DYNDNS_CHAIN
 
@@ -44,6 +50,7 @@ dyndns_host_open_helper_setup_rules()
         # get_dynamic_host_cached returns hostname in $host_ip
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping TCP rule(s) for \"$host\"! **" >&2
+          RETVAL=1
           continue
         fi
         for interface in $interfaces; do
@@ -69,6 +76,7 @@ dyndns_host_open_helper_setup_rules()
         # get_dynamic_host_cached returns hostname in $host_ip
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping UDP rule(s) for \"$host\"! **" >&2
+          RETVAL=1
           continue
         fi
         for interface in $interfaces; do
@@ -94,6 +102,7 @@ dyndns_host_open_helper_setup_rules()
         # get_dynamic_host_cached returns hostname in $host_ip
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping IP rule(s) for \"$host\"! **" >&2
+          RETVAL=1
           continue
         fi
         for interface in $interfaces; do
@@ -119,6 +128,7 @@ dyndns_host_open_helper_setup_rules()
         # get_dynamic_host_cached returns hostname in $host_ip
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping ICMP rule(s) for \"$host\"! **" >&2
+          RETVAL=1
           continue
         fi
 
@@ -130,6 +140,8 @@ dyndns_host_open_helper_setup_rules()
       done
     fi
   done
+
+  return $RETVAL
 }
 
 
@@ -143,22 +155,21 @@ if [ -n "$PLUGIN_CONF_PATH" ]; then
   CONF_FILE="$PLUGIN_CONF_PATH/$PLUGIN_CONF_FILE"
 fi
 
-# Preinit return value for success
-PLUGIN_RET_VAL=0
-
 # Check if the config file exists
 if [ ! -e "$CONF_FILE" ]; then
   echo "** ERROR: Config file \"$CONF_FILE\" not found! **" >&2
   PLUGIN_RET_VAL=1
-else
-  # Source the plugin config file
-  . "$CONF_FILE"
+fi
 
-  # Only proceed if environment ok
-  if dyndns_host_open_helper_sanity_check; then
-    # Parse rules
-    dyndns_host_open_helper_setup_rules
-  else
-    PLUGIN_RET_VAL=1
-  fi
+# Source the plugin config file
+. "$CONF_FILE"
+
+# Only proceed if environment ok
+if ! dyndns_host_open_helper_sanity_check; then
+  PLUGIN_RET_VAL=1
+fi
+
+# Parse rules
+if ! dyndns_host_open_helper_setup_rules; then
+  PLUGIN_RET_VAL=1
 fi
diff --git a/share/arno-iptables-firewall/plugins/parasitic-net-helper b/share/arno-iptables-firewall/plugins/parasitic-net-helper
--- a/share/arno-iptables-firewall/plugins/parasitic-net-helper
+++ b/share/arno-iptables-firewall/plugins/parasitic-net-helper
@@ -2,6 +2,10 @@
 ###############################
 PLUGIN_CONF_FILE="parasitic-net.conf"
 
+# Preinit return value for success
+PLUGIN_RET_VAL=0
+
+
 # Check sanity of eg. environment
 parasitic_net_sanity_check()
 {
@@ -17,6 +21,8 @@ parasitic_net_sanity_check()
 
 parasitic_net_setup_rules()
 {
+  local RETVAL=0
+
   # Flush the PARASITIC_NET_ACL
   iptables -F PARASITIC_NET_ACL
 
@@ -29,6 +35,7 @@ parasitic_net_setup_rules()
       for host in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping TCP rule(s) for \"$host\"! **" >&2
+          RETVAL=1
           continue
         fi
 
@@ -53,6 +60,7 @@ parasitic_net_setup_rules()
       for host in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping TCP rule(s) for \"$host\"! **" >&2
+          RETVAL=1
           continue
         fi
 
@@ -75,6 +83,7 @@ parasitic_net_setup_rules()
     for host in `ip_range "$hosts"`; do
       if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
         echo "** WARNING: Skipping TCP rule(s) for \"$host\"! **" >&2
+        RETVAL=1
         continue
       fi
 
@@ -91,6 +100,7 @@ parasitic_net_setup_rules()
   for rule in $PARASITIC_NET_HOST_DENY_IP; do
     if parse_rule "$rule" PARASITIC_NET_HOST_DENY_IP "hosts-protos"; then
       echo "${INDENT}Denying access to $hosts for IP protocol(s): $protos"
+      RETVAL=1
       IFS=','
       for host in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
@@ -119,6 +129,7 @@ parasitic_net_setup_rules()
       for host in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping TCP rule(s) for \"$host\"! **" >&2
+          RETVAL=1
           continue
         fi
 
@@ -138,6 +149,7 @@ parasitic_net_setup_rules()
       for host in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping TCP rule(s) for \"$host\"! **" >&2
+          RETVAL=1
           continue
         fi
 
@@ -155,6 +167,7 @@ parasitic_net_setup_rules()
     for host in `ip_range "$hosts"`; do
       if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
         echo "** WARNING: Skipping TCP rule(s) for \"$host\"! **" >&2
+        RETVAL=1
         continue
       fi
 
@@ -171,6 +184,7 @@ parasitic_net_setup_rules()
       for host in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping TCP rule(s) for \"$host\"! **" >&2
+          RETVAL=1
           continue
         fi
 
@@ -221,6 +235,8 @@ parasitic_net_setup_rules()
       --log-level $LOGLEVEL --log-prefix "AIF:Parasitic-net denied: "
   fi
   ip4tables -A PARASITIC_NET_ACL -j $PARASITIC_NET_DENY_POLICY
+
+  return $RETVAL
 }
 
 
@@ -234,22 +250,21 @@ if [ -n "$PLUGIN_CONF_PATH" ]; then
   CONF_FILE="$PLUGIN_CONF_PATH/$PLUGIN_CONF_FILE"
 fi
 
-# Preinit return value for success
-PLUGIN_RET_VAL=0
-
 # Check if the config file exists
 if [ ! -e "$CONF_FILE" ]; then
   echo "** ERROR: Config file \"$CONF_FILE\" not found! **" >&2
   PLUGIN_RET_VAL=1
-else
-  # Source the plugin config file
-  . "$CONF_FILE"
+fi
 
-  # Only proceed if environment ok
-  if parasitic_net_sanity_check; then
-    # Create actual rules
-    parasitic_net_setup_rules
-  else
-    PLUGIN_RET_VAL=1
-  fi
+# Source the plugin config file
+. "$CONF_FILE"
+
+# Only proceed if environment ok
+if ! parasitic_net_sanity_check; then
+  PLUGIN_RET_VAL=1
+fi
+
+# Create actual rules
+if ! parasitic_net_setup_rules; then
+  PLUGIN_RET_VAL=1
 fi
diff --git a/share/arno-iptables-firewall/plugins/traffic-accounting-helper b/share/arno-iptables-firewall/plugins/traffic-accounting-helper
--- a/share/arno-iptables-firewall/plugins/traffic-accounting-helper
+++ b/share/arno-iptables-firewall/plugins/traffic-accounting-helper
@@ -2,12 +2,12 @@
 ###############################
 PLUGIN_CONF_FILE="traffic-accounting.conf"
 
+# Preinit return value for success
+PLUGIN_RET_VAL=0
+
 # Define some global variables
 VERBOSE=0
 
-if [ "$1" = "-v" -o "$1" = "--verbose" ]; then
-  VERBOSE=1
-fi
 
 # Check sanity of eg. environment
 traffic_accounting_helper_sanity_check()
@@ -40,6 +40,8 @@ traffic_accounting_helper_sanity_check()
 
 traffic_accounting_setup_rules()
 {
+  local RETVAL=0
+
   # Touch the log file (just in case it doesn't exist yet):
   touch /var/log/traffic-accounting.log
 
@@ -84,6 +86,7 @@ traffic_accounting_setup_rules()
     # NOTE: get_dynamic_host_cached returns hostname in $host_ip
     if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
       echo "** WARNING: Skipping rule for \"$host\"! **" >&2
+      RETVAL=1
       continue
     fi
 
@@ -245,6 +248,8 @@ traffic_accounting_setup_rules()
     mv /var/log/traffic-accounting.log /var/log/traffic-accounting.log.old
   fi
   mv /tmp/traffic-accounting.new /var/log/traffic-accounting.log
+
+  return $RETVAL
 }
 
 
@@ -252,28 +257,31 @@ traffic_accounting_setup_rules()
 # Mainline #
 ############
 
+if [ "$1" = "-v" -o "$1" = "--verbose" ]; then
+  VERBOSE=1
+fi
+
 # Check where to find the config file
 CONF_FILE=""
 if [ -n "$PLUGIN_CONF_PATH" ]; then
   CONF_FILE="$PLUGIN_CONF_PATH/$PLUGIN_CONF_FILE"
 fi
 
-# Preinit return value for success
-PLUGIN_RET_VAL=0
-
 # Check if the config file exists
 if [ ! -e "$CONF_FILE" ]; then
   echo "** ERROR: Config file \"$CONF_FILE\" not found! **" >&2
   PLUGIN_RET_VAL=1
-else
-  # Source the plugin config file
-  . "$CONF_FILE"
+fi
 
-  # Only proceed if environment ok
-  if traffic_accounting_helper_sanity_check; then
-    # Create actual rules
-    traffic_accounting_setup_rules
-  else
-    PLUGIN_RET_VAL=1
-  fi
+# Source the plugin config file
+. "$CONF_FILE"
+
+# Only proceed if environment ok
+if ! traffic_accounting_helper_sanity_check; then
+  PLUGIN_RET_VAL=1
+fi
+
+# Create actual rules
+if ! traffic_accounting_setup_rules; then
+  PLUGIN_RET_VAL=1
 fi
