fixed: Formatting changed: Error message on DNS server fail
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/trunk@678 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
--- a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
+++ b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
@@ -100,15 +100,12 @@ dyndns_get_host_cached()
   
   printf "${INDENT}Resolving host \"$host\" -> "
 
-    host_ip=`gethostbyname "$host"`
-    retval=$?
-      
-    # Check whether our DNS server itself failed
-    if [ $retval -eq 9 ]; then
-        echo "** ERROR(9): DNS server connection failed! **" >&2
-    fi
-     
+  host_ip=`gethostbyname "$host"`
+  retval=$?
+    
   if [ -z "$host_ip" -o $retval -ne 0 ]; then
+    echo "** ERROR($retval): DNS query failed! **" >&2
+    
     # Try to get from (old) cache, if allowed
     if [ "$DYNDNS_OLD_CACHE_FALLBACK" = "1" ]; then
       host_ip=`grep "^$host " -m1 "${DYNDNS_HOST_CACHE}" |cut -s -f2 -d' '`
