added: in dyndns-host-open-helper the same main chain sanity check as for the accounting-plugin-helper
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/branches/1.9.9@459 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
--- a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
+++ b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
@@ -60,6 +60,12 @@ sanity_check()
     return 1
   fi
 
+  # Check if chain is inserted in the main chains
+  if ! iptables -nL EXT_INPUT_CHAIN |grep -q '^DYNDNS_CHAIN '; then
+    echo "** ERROR: DYNDNS_CHAIN is not inserted in the EXT_INPUT_CHAIN chain! **" >&2
+    return 1
+  fi
+
   if ! check_command dig nslookup; then
     echo "** ERROR: Required command dig (or nslookup) is not available!" >&2
     return 1
