changed: Detect and remove stale lockfiles

diff --git a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
--- a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
+++ b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
@@ -314,10 +314,20 @@ else
     # Only proceed if environment ok
     if sanity_check; then
       # This is a critical section so we use a lockfile
-      lockfile="/var/tmp/aif_dyndns_helper.lock"
-      if ( set -o noclobber; echo "$$" > "$lockfile") 2> /dev/null; then
+      LOCK_FILE="/var/tmp/aif_dyndns_helper.lock"
+
+      # Check for stale LOCK file
+      if [ -e "$LOCK_FILE" ]; then
+        PID="$(cat "$LOCK_FILE")"
+        if [ -z "$PID" ] || ! ps -o "%p %u %c %a" $PID; then
+          rm -f "$LOCK_FILE"
+          echo "Note: Removed stale lockfile: $LOCK_FILE" >&2
+        fi
+      fi
+
+      if (set -o noclobber; echo "$$" > "$LOCK_FILE") 2> /dev/null; then
         # Setup int handler
-        trap 'rm -f "$lockfile"; exit $?' INT TERM EXIT
+        trap 'rm -f "$LOCK_FILE"; exit $?' INT TERM EXIT
 
         # Create new empty file
         printf "" >"${DYNDNS_HOST_CACHE}.new"
@@ -332,15 +342,16 @@ else
         mv "${DYNDNS_HOST_CACHE}.new" "$DYNDNS_HOST_CACHE"
 
         # Remove lockfile
-        rm -f "$lockfile"
+        rm -f "$LOCK_FILE"
 
         # Disable int handler
         trap - INT TERM EXIT
 
         exit 0
       else
-        echo "Failed to acquire lockfile: $lockfile." >&2
-        echo "Held by $(cat $lockfile)" >&2
+        echo "Failed to acquire lockfile: $LOCK_FILE" >&2
+        PROCESS="$(ps -o "%p %u %c %a" "$(cat "$LOCK_FILE")")"
+        printf "Held by:\n${PROCESS}\n" >&2
       fi
     fi
   fi
