merged: New DynDNS & Traffic Accounting plugins from the WIP-branch
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/trunk@176 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
--- a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
+++ b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
@@ -36,44 +36,131 @@ else
   fi
 fi
 
+# Define some global variables
+DYNDNS_HOST_CACHE="/var/tmp/aif-dyndns-host-cache"
+DNS_SERVER_FAILURE=0
+INDENT='   '
 
-# Check sanity of eg. environment
+# Check sanity of environment
 sanity_check()
 {
   if [ -z "$DYNDNS_HOST_OPEN_CRON" ]; then
-    echo "** ERROR: The plugin config file is not properly set!" >&2
+    echo "** ERROR: The plugin config file is not properly setup!" >&2
+    return 1
+  fi
+
+  if [ -z "$DYNDNS_HOST_OPEN_TCP" ] && [ -z "$DYNDNS_HOST_OPEN_UDP" ] && [ -z "$DYNDNS_HOST_OPEN_IP" ] && [ -z "$DYNDNS_HOST_OPEN_ICMP" ]; then
+    echo "** ERROR: The plugin config file is not (properly) setup!" >&2
     return 1
   fi
 
   # Check whether chain exists
-  if ! iptables -nL DYNDNS_CHAIN 2>&1 >/dev/null; then
+  if ! iptables -nL DYNDNS_CHAIN >/dev/null 2>&1; then
     echo "** ERROR: DYNDNS_CHAIN does not exist! **" >&2
     return 1
   fi
 
+  return 0
+}
+
+
+# Resolve a hostname using our cache
+dyndns_get_cached_host()
+{
+  local host="$1"
+  
+  if [ -e "$DYNDNS_HOST_CACHE" ]; then
+    local host_ip=`grep "^$host " -m1 "$DYNDNS_HOST_CACHE" |cut -s -f2 -d' '`
+    if [ -n "$host_ip" ]; then
+      echo "$host_ip"
+      return 0
+    fi
+  fi
+  
+  # Return error
+  return 1
+}
+
+
+# Resolve hostname to IP and store both in our (new) cache
+dyndns_host_to_cache()
+{
+  local host="$1"
+  local host_ip=""
+  
+  # Check whether we already have it in our (new) cache
+  if ! grep -q "^$host " "$DYNDNS_HOST_CACHE".new; then
+    printf "${INDENT}Resolving host \"$host\" -> "
+
+    if [ "$DNS_SERVER_FAILURE" = "1" ]; then
+      echo "** WARNING: Not quering DNS server since it is considered dead for this session! **" >&2 
+      host_ip=""
+      retval=9
+    else
+      host_ip=`gethostbyname "$host"`
+      retval=$?
+      
+      # Check whether our DNS server itself failed
+      if [ "$retval" = "9" ]; then
+        if [ "$DYNDNS_SESSION_FAILED_DNS_SKIP" = "1" ]; then
+          # The DNS server failed, so set flag so we know this the next time
+          DNS_SERVER_FAILURE=1
+          echo "** ERROR(9): DNS server connection failed! Assuming server dead for this session. **" >&2 
+        else
+          echo "** ERROR(9): DNS server connection failed! **" >&2 
+        fi
+      fi
+    fi
+     
+    if [ -z "$host_ip" ]; then
+      # Try to get from (old) cache, if allowed
+      if [ "$DYNDNS_OLD_CACHE_FALLBACK" = "1" ]; then
+        host_ip=`dyndns_get_cached_host $host`
+      fi
+      
+      # (Re)check $host_ip
+      if [ -z "$host_ip" ]; then
+        printf "\033[40m\033[1;31mFAILED!\033[0m\n"
+        echo "** ERROR($retval): Unresolvable host \"$host\", and no old IP to fallback on! **" >&2 
+      
+        # Create dummy entry, so the others know we failed
+        echo "$host " >>"$DYNDNS_HOST_CACHE".new
+        return $retval
+      else
+        echo "** WARNING($retval): Unresolvable host \"$host\". Re-using old IP ($host_ip)! **" >&2 
+      fi
+    fi
+    echo "$host_ip"
+    echo "$host $host_ip" >>"$DYNDNS_HOST_CACHE".new 
+  fi
+  
+  return 0
+}      
+
+
+# Setup host->ip cache
+dyndns_setup_cache()
+{
+  # Create new empty file
+  printf "" >"$DYNDNS_HOST_CACHE".new
+  
   unset IFS
   for rule in $DYNDNS_HOST_OPEN_TCP; do
     hosts=`get_hosts_ihp "$rule"`
-
+    
     IFS=','
     for host in $hosts; do
-      if [ -z "$(gethostbyname "$host")" ]; then
-        echo "** ERROR: Unresolvable host \"$host\", refusing to (re)start!" >&2
-        return 1
-      fi
+      dyndns_host_to_cache "$host"
     done
   done
 
   unset IFS
   for rule in $DYNDNS_HOST_OPEN_UDP; do
     hosts=`get_hosts_ihp "$rule"`
-
+   
     IFS=','
     for host in $hosts; do
-      if [ -z "$(gethostbyname "$host")" ]; then
-        echo "** ERROR: Unresolvable host \"$host\", refusing to (re)start!" >&2
-        return 1
-      fi
+      dyndns_host_to_cache "$host"
     done
   done
 
@@ -81,28 +168,28 @@ sanity_check()
   for rule in $DYNDNS_HOST_OPEN_IP; do
     hosts=`get_hosts_ihp "$rule"`
 
-    IFS=','
+    IFS=','    
     for host in $hosts; do
-      if [ -z "$(gethostbyname "$host")" ]; then
-        echo "** ERROR: Unresolvable host \"$host\", refusing to (re)start!" >&2
-        return 1
-      fi
+      dyndns_host_to_cache "$host"
     done
   done
 
-  IFS=" ,"
+  IFS=' ,'
   for rule in $DYNDNS_HOST_OPEN_ICMP; do
     hosts=`get_hosts_ih "$rule"`
 
     IFS=','
     for host in $hosts; do
-      if [ -z "$(gethostbyname "$host")" ]; then
-        echo "** ERROR: Unresolvable host \"$host\", refusing to (re)start!" >&2
-        return 1
-      fi
+      dyndns_host_to_cache "$host"
     done
   done
 
+  # Remove old cache file
+  rm -f "$DYNDNS_HOST_CACHE" 2>/dev/null
+  
+  # Make our new cache file active
+  mv "$DYNDNS_HOST_CACHE".new "$DYNDNS_HOST_CACHE"
+  
   return 0
 }
 
@@ -121,14 +208,17 @@ dyndns_host_open()
     hosts=`get_hosts_ihp "$rule"`
     ports=`get_ports_ihp "$rule"`
 
-    echo "$(show_if_ip "$interfaces" "$destips")Allowing $hosts for TCP port(s): $ports"
-
+    echo "${INDENT}$(show_if_ip "$interfaces" "$destips")Allowing $hosts for TCP port(s): $ports"
+    
     IFS=','
-    for host in $hosts; do
-      for port in $ports; do
-        for destip in $destips; do
-          for interface in $interfaces; do
-            iptables -A DYNDNS_CHAIN -i $interface -s $(gethostbyname "$host") -d $destip -p tcp --dport $port -j ACCEPT
+    for interface in $interfaces; do
+      for destip in $destips; do
+        for host in $hosts; do
+          for port in $ports; do
+            host_ip=`dyndns_get_cached_host $host`
+            if [ -n "$host_ip" ]; then
+              iptables -A DYNDNS_CHAIN -i $interface -s $host_ip -d $destip -p tcp --dport $port -j ACCEPT
+            fi
           done
         done
       done
@@ -145,14 +235,17 @@ dyndns_host_open()
     hosts=`get_hosts_ihp "$rule"`
     ports=`get_ports_ihp "$rule"`
 
-    echo "$(show_if_ip "$interfaces" "$destips")Allowing $hosts for UDP port(s): $ports"
-
+    echo "${INDENT}$(show_if_ip "$interfaces" "$destips")Allowing $hosts for UDP port(s): $ports"
+    
     IFS=','
-    for host in $hosts; do
-      for port in $ports; do
-        for destip in $destips; do
-          for interface in $interfaces; do
-            iptables -A DYNDNS_CHAIN -i $interface -s $(gethostbyname "$host") -d $destip -p udp --dport $port -j ACCEPT
+    for interface in $interfaces; do
+      for destip in $destips; do
+        for host in $hosts; do
+          for port in $ports; do
+            host_ip=`dyndns_get_cached_host $host`
+            if [ -n "$host_ip" ]; then
+              iptables -A DYNDNS_CHAIN -i $interface -s $host_ip -d $destip -p udp --dport $port -j ACCEPT
+            fi
           done
         done
       done
@@ -169,15 +262,17 @@ dyndns_host_open()
     hosts=`get_hosts_ihp "$rule"`
     protos=`get_ports_ihp "$rule"`
 
-    echo "$(show_if_ip "$interfaces" "$destips")Allowing $hosts for IP protocol(s): $protos"
-
+    echo "${INDENT}$(show_if_ip "$interfaces" "$destips")Allowing $hosts for IP protocol(s): $protos"
+    
     IFS=','
-    for host in $hosts; do
-      IFS=','
-      for proto in $protos; do
-        for destip in $destips; do
-          for interface in $interfaces; do
-            iptables -A DYNDNS_CHAIN -i $interface -s $(gethostbyname "$host") -d $destip -p $proto -j ACCEPT
+    for interface in $interfaces; do
+      for destip in $destips; do
+        for host in $hosts; do
+          for proto in $protos; do
+            host_ip=`dyndns_get_cached_host $host`
+            if [ -n "$host_ip" ]; then
+              iptables -A DYNDNS_CHAIN -i $interface -s $host_ip -d $destip -p $proto -j ACCEPT
+            fi
           done
         done
       done
@@ -193,22 +288,21 @@ dyndns_host_open()
     destips=`get_ips "$rule"`
     hosts=`get_hosts_ih "$rule"`
 
-    echo "$(show_if_ip "$interfaces" "$destips")Allowing $hosts for ICMP-requests(ping)"
-
+    echo "${INDENT}$(show_if_ip "$interfaces" "$destips")Allowing $hosts for ICMP-requests(ping)"
+    
     IFS=','
-    for host in $hosts; do
+    for interface in $interfaces; do
       for destip in $destips; do
-        for interface in $interfaces; do
-          iptables -A DYNDNS_CHAIN -i $interface -s $(gethostbyname "$host") -d $destip -p $ICMP_PROTO $ICMP_TYPE echo-request -j ACCEPT
+        for host in $hosts; do
+          host_ip=`dyndns_get_cached_host $host`
+          if [ -n "$host_ip" ]; then
+            iptables -A DYNDNS_CHAIN -i $interface -s $host_ip -d $destip -p $ICMP_PROTO $ICMP_TYPE echo-request -j ACCEPT
+          fi
         done
       done
     done
   done
-
-  return 0
 }
-
-
 
 
 ############
@@ -232,13 +326,11 @@ else
 
   if [ "$ENABLED" = "1" ]; then
     # Only proceed if environment ok
-    if sanity_check; then
-      dyndns_host_open;
-    else
-#      printf "  ** ERROR: Sanity check failed! **" >&2
-      exit 1
-    fi
+    sanity_check       &&
+    dyndns_setup_cache &&
+    dyndns_host_open   &&
+    exit 0;
   fi
 fi
 
-exit 0
+exit 1
diff --git a/share/arno-iptables-firewall/plugins/traffic-accounting-helper b/share/arno-iptables-firewall/plugins/traffic-accounting-helper
--- a/share/arno-iptables-firewall/plugins/traffic-accounting-helper
+++ b/share/arno-iptables-firewall/plugins/traffic-accounting-helper
@@ -36,6 +36,15 @@ else
   fi
 fi
 
+# Define some global variables
+TRAFFIC_ACCOUNTING_HOST_CACHE="/var/tmp/aif-traffic-accounting-host-cache"
+DNS_SERVER_FAILURE=0
+INDENT='   '
+VERBOSE=0
+
+if [ "$1" = "-v" ]; then
+  VERBOSE=1
+fi
 
 # Check sanity of eg. environment
 sanity_check()
@@ -70,22 +79,120 @@ sanity_check()
   return 0
 }
 
-
-traffic_accounting()
+# Resolve a hostname using our cache
+traffic_accounting_get_cached_host()
 {
-  # Touch the log files (just in case they don't exist yet):
+  local host="$1"
+  
+  if [ -e "$TRAFFIC_ACCOUNTING_HOST_CACHE" ]; then
+    local host_ip=`grep "^$host " -m1 "$TRAFFIC_ACCOUNTING_HOST_CACHE" |cut -s -f2 -d' '`
+    if [ -n "$host_ip" ]; then
+      echo "$host_ip"
+      return 0
+    fi
+  fi
+  
+  # Return error
+  return 1
+}
+
+
+# Resolve hostname to IP and store both in our (new) cache
+traffic_accounting_host_to_cache()
+{
+  local host="$1"
+  local host_ip=""
+  local retval=0
+  
+  # Check whether we already have it in our (new) cache
+  if ! grep -q "^$host " "$TRAFFIC_ACCOUNTING_HOST_CACHE".new; then
+    printf "${INDENT}Resolving host \"$host\" -> "
+
+    if [ "$DNS_SERVER_FAILURE" = "1" ]; then
+      echo "** WARNING: Not quering DNS server since it is considered dead for this session! **" >&2 
+      host_ip=""
+      retval=9
+    else
+      host_ip=`gethostbyname "$host"`
+      retval=$?
+      
+      # Check whether our DNS server itself failed
+      if [ "$retval" = "9" ]; then
+        if [ "$TRAFFIC_ACCOUNTING_SESSION_FAILED_DNS_SKIP" = "1" ]; then
+          # The DNS server failed, so set flag so we know this the next time
+          DNS_SERVER_FAILURE=1
+          echo "** ERROR(9): DNS server connection failed! Assuming server dead for this session. **" >&2 
+        else
+          echo "** ERROR(9): DNS server connection failed! **" >&2 
+        fi
+      fi
+    fi
+     
+    if [ -z "$host_ip" ]; then
+      # Try to get from (old) cache, if allowed
+      if [ "$TRAFFIC_ACCOUNTING_OLD_CACHE_FALLBACK" = "1" ]; then
+        host_ip=`dyndns_get_cached_host $host`
+      fi
+      
+      # (Re)check $host_ip
+      if [ -z "$host_ip" ]; then
+        printf "\033[40m\033[1;31mFAILED!\033[0m\n"
+        echo "** ERROR($retval): Unresolvable host \"$host\", and no old IP to fallback on! **" >&2 
+      
+        # Create dummy entry, so the others know we failed
+        echo "$host " >>"$TRAFFIC_ACCOUNTING_HOST_CACHE".new
+        return $retval
+      else
+        echo "** WARNING($retval): Unresolvable host \"$host\". Re-using old IP ($host_ip)! **" >&2 
+      fi
+    fi
+    echo "$host_ip"
+    echo "$host $host_ip" >>"$TRAFFIC_ACCOUNTING_HOST_CACHE".new 
+  fi
+  
+  return 0
+}      
+
+# Setup host->ip cache
+traffic_accounting_setup_cache()
+{
+  # Create new empty file
+  printf "" >"$TRAFFIC_ACCOUNTING_HOST_CACHE".new
+  
+  IFS=' ,'
+  for host in $TRAFFIC_ACCOUNTING_HOSTS; do
+    traffic_accounting_host_to_cache "$host"
+  done
+
+  # Remove old cache file
+  rm -f "$TRAFFIC_ACCOUNTING_HOST_CACHE" 2>/dev/null
+  
+  # Make our new cache file active
+  mv "$TRAFFIC_ACCOUNTING_HOST_CACHE".new "$TRAFFIC_ACCOUNTING_HOST_CACHE"
+}
+
+
+traffic_accounting_setup_rules()
+{
+  # Touch the log file (just in case they doesn't exist yet):
   touch /var/log/traffic-accounting.log
 
   # Truncate file
   printf "" >/tmp/traffic-accounting.new
 
   # Process the input chain
-  echo "Traffic Accounting Hosts:"
-  echo "-------------------------"
+  if [ "$VERBOSE" = "1" ]; then
+    echo "Traffic Accounting Hosts:"
+    echo "-------------------------"
+  fi
+  
   IFS=' ,'
   # Also add catch all rule (0.0.0.0/0)
   for host in $TRAFFIC_ACCOUNTING_HOSTS 0.0.0.0/0; do
-    printf "Host=$host "
+    if [ "$VERBOSE" = "1" ]; then
+      printf "Host=$host "
+    fi
+    
     old_entry="$(grep "^$host " /var/log/traffic-accounting.log)"
     old_ip="$(echo "$old_entry" |cut -s -d' ' -f2)"
     old_in_value="$(echo "$old_entry" |cut -s -d' ' -f3)"
@@ -102,21 +209,21 @@ traffic_accounting()
     fi
 
     # Get host ip
-    new_ip=`gethostbyname "$host"`
+    if is_numeric_ipv4 "$host" || is_numeric_ipv6 "$host"; then
+      new_ip="$host"
+    else
+      new_ip=`traffic_accounting_get_cached_host "$host"`
+    fi
 
     # If it fails use old IP
     if [ -z "$new_ip" ]; then
-      if [ -n "$old_ip" ]; then
-        echo "** ERROR: Unresolvable host \"$host\". Re-using old IP! **" >&2
-        new_ip="$old_ip"
-      else
-        echo "** ERROR: Unresolvable host \"$host\", and no old IP to fallback on! **" >&2
-        # TODO: continue here?
-        return 1
-      fi
+      echo "** WARNING: Unresolvable host \"$host\", and no old IP to fallback on. Skipping host!... **" >&2
+      continue;
     fi
 
-    printf "old_ip=$old_ip new_ip=$new_ip "
+    if [ "$VERBOSE" = "1" ]; then
+      printf "old_ip=$old_ip new_ip=$new_ip "
+    fi
 
     # Process input chain
     OLDFOUND=0
@@ -129,7 +236,9 @@ traffic_accounting()
         LCOUNT=$(($LCOUNT + 1))
         if [ "$ipt_ip" = "$old_ip" ]; then
           iptables -R ACCOUNTING_INPUT_CHAIN $LCOUNT -s $new_ip -j RETURN
-          printf "in_action=update "
+          if [ "$VERBOSE" = "1" ]; then
+            printf "in_action=update "
+          fi
           OLDFOUND=1
           ipt_in_value="$(echo "$LINE" |awk '{ print $2 }')"
 
@@ -139,7 +248,9 @@ traffic_accounting()
     fi
 
     if [ "$OLDFOUND" = "0" ]; then
-      printf "in_action=add "
+      if [ "$VERBOSE" = "1" ]; then
+        printf "in_action=add "
+      fi
       iptables -A ACCOUNTING_INPUT_CHAIN -s $new_ip -j RETURN
 
       # Preset values to zero as none exist yet
@@ -157,7 +268,9 @@ traffic_accounting()
         LCOUNT=$(($LCOUNT + 1))
         if [ "$ipt_ip" = "$old_ip" ]; then
           iptables -R ACCOUNTING_OUTPUT_CHAIN $LCOUNT -d $new_ip -j RETURN
-          printf "out_action=update "
+          if [ "$VERBOSE" = "1" ]; then
+            printf "out_action=update "
+          fi
           OLDFOUND=1
           ipt_out_value="$(echo "$LINE" |awk '{ print $2 }')"
 
@@ -167,7 +280,9 @@ traffic_accounting()
     fi
 
     if [ "$OLDFOUND" = "0" ]; then
-      printf "out_action=add "
+      if [ "$VERBOSE" = "1" ]; then
+        printf "out_action=add "
+      fi
       iptables -A ACCOUNTING_OUTPUT_CHAIN -d $new_ip -j RETURN
 
       # Preset values to zero as none exist yet
@@ -179,15 +294,19 @@ traffic_accounting()
 
     # Calculate new out value
     new_out_value=$(($old_out_value + $ipt_out_value))
-
-    printf "old_in_val=$old_in_value ipt_in_val=$ipt_in_value new_in_val=$new_in_value old_out_val=$old_out_value ipt_out_val=$ipt_out_value new_out_val=$new_out_value"
-
+    if [ "$VERBOSE" = "1" ]; then
+      printf "old_in_val=$old_in_value ipt_in_val=$ipt_in_value new_in_val=$new_in_value old_out_val=$old_out_value ipt_out_val=$ipt_out_value new_out_val=$new_out_value"
+    fi
+    
     # Create entry in accounting file
     echo "$host $new_ip $new_in_value $new_out_value" >>/tmp/traffic-accounting.new
 
-    printf "\n\n"
+    if [ "$VERBOSE" = "1" ]; then
+      printf "\n\n"
+    fi
   done
-
+  
+  # FIXME: Don't use old-file
   if [ -e /var/log/traffic-accounting.log ]; then
     if [ -e /var/log/traffic-accounting.log.old ]; then
       rm -f /var/log/traffic-accounting.log.old
@@ -212,7 +331,7 @@ fi
 
 # Check if the config file exists
 if [ ! -e "$CONF_FILE" ]; then
-  printf "  ** ERROR: Config file \"$CONF_FILE\" not found! **\n" >&2
+  echo "** ERROR: Config file \"$CONF_FILE\" not found! **" >&2
   exit 1
 else
   # Source the plugin config file
@@ -228,23 +347,23 @@ else
         trap 'rm -f "$lockfile"; exit $?' INT TERM EXIT
 
         # Call our function
-        traffic_accounting;
+        traffic_accounting_setup_cache
+        traffic_accounting_setup_rules
+        ret=$?
 
         # Remove lockfile
         rm -f "$lockfile"
 
         # Disable int handler
         trap - INT TERM EXIT
+        
+        exit $ret
       else
         echo "Failed to acquire lockfile: $lockfile." >&2
         echo "Held by $(cat $lockfile)" >&2
-        exit 1
       fi
-    else
-#      printf "  ** ERROR: Sanity check failed! **" >&2
-      exit 1
     fi
   fi
 fi
 
-exit 0
+exit 1
