fixed: Checking for chains in eg. INPUT doesn't work when called for eg. a plugin restart

diff --git a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
--- a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
+++ b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
@@ -66,10 +66,10 @@ sanity_check()
   fi
 
   # Check if chain is inserted in the main chains
-  if ! ip4tables -nL EXT_INPUT_CHAIN |grep -q '^DYNDNS_CHAIN '; then
-    echo "** ERROR: DYNDNS_CHAIN is not inserted in the EXT_INPUT_CHAIN chain! **" >&2
-    return 1
-  fi
+#  if ! ip4tables -nL EXT_INPUT_CHAIN |grep -q '^DYNDNS_CHAIN '; then
+#    echo "** ERROR: DYNDNS_CHAIN is not inserted in the EXT_INPUT_CHAIN chain! **" >&2
+#    return 1
+#  fi
 
   if ! check_command dig nslookup; then
     echo "** ERROR: Required command dig (or nslookup) is not available!" >&2
diff --git a/share/arno-iptables-firewall/plugins/traffic-accounting-helper b/share/arno-iptables-firewall/plugins/traffic-accounting-helper
--- a/share/arno-iptables-firewall/plugins/traffic-accounting-helper
+++ b/share/arno-iptables-firewall/plugins/traffic-accounting-helper
@@ -67,15 +67,15 @@ sanity_check()
   fi
 
   # Check if chains inserted in the main chains
-  if ! ip4tables -nL INPUT |grep -q '^ACCOUNTING_INPUT_CHAIN '; then
-    echo "** ERROR: ACCOUNTING_INPUT_CHAIN is not inserted in the INPUT chain! **" >&2
-    return 1
-  fi
+#  if ! ip4tables -nL INPUT |grep -q '^ACCOUNTING_INPUT_CHAIN '; then
+#    echo "** ERROR: ACCOUNTING_INPUT_CHAIN is not inserted in the INPUT chain! **" >&2
+#    return 1
+#  fi
 
-  if ! ip4tables -nL OUTPUT |grep -q '^ACCOUNTING_OUTPUT_CHAIN '; then
-    echo "** ERROR: ACCOUNTING_OUTPUT_CHAIN is not inserted in the OUTPUT chain! **" >&2
-    return 1
-  fi
+#  if ! ip4tables -nL OUTPUT |grep -q '^ACCOUNTING_OUTPUT_CHAIN '; then
+#    echo "** ERROR: ACCOUNTING_OUTPUT_CHAIN is not inserted in the OUTPUT chain! **" >&2
+#    return 1
+#  fi
 
   if ! check_command dig nslookup; then
     echo "** ERROR: Required command dig (or nslookup) is not available!" >&2
