[WIP] changed: Several tweaks + extra options for our new DynDNS plugin
git-svn-id: https://rocky.eld.leidenuniv.nl/svn/aif/branches/wip@124 2cdb06df-4b6c-47a8-a790-b77aef9f425a

diff --git a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
--- a/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
+++ b/share/arno-iptables-firewall/plugins/dyndns-host-open-helper
@@ -36,8 +36,9 @@ else
   fi
 fi
 
-# Define our host cache file
+# Define some global variables
 DYNDNS_HOST_CACHE="/var/tmp/aif-dyndns-host-cache"
+DNS_SERVER_FAILURE=0
 INDENT='  '
 
 # Check sanity of environment
@@ -86,15 +87,32 @@ dyndns_get_cached_host()
 dyndns_host_to_cache()
 {
   local host="$1"
+  local host_ip=""
   
   # Check whether we already have it in our (new) cache
   if ! grep -q "^$host " "$DYNDNS_HOST_CACHE".new; then
     printf "${INDENT}Resolving host \"$host\"..."
-    # Set short timeout(1) and only retry once(1), else it could ages to process
-    # in case of errors
-    host_ip=`gethostbyname "$host" +tries=1 +time=1`
-    retval=$?
-    
+
+    if [ "$DNS_SERVER_FAILURE" = "1" ]; then
+      echo "** WARNING($retval): Not quering DNS server since it is considered dead for this session! **" >&2 
+      host_ip=""
+      retval=9
+    else
+      host_ip=`gethostbyname "$host"`
+      retval=$?
+      
+      # Check whether our DNS server itself failed
+      if [ "$retval" = "9" ]; then
+        if [ "$DYNDNS_SESSION_FAILED_DNS_SKIP" = "1" ]; then
+          # The DNS server failed, so set flag so we know this the next time
+          DNS_SERVER_FAILURE=1
+          echo "** ERROR(9): DNS server connection failed! Assuming server dead for this session. **" >&2 
+        else
+          echo "** ERROR(9): DNS server connection failed! **" >&2 
+        fi
+      fi
+    fi
+     
     if [ -z "$host_ip" ]; then
       # Try to get from (old) cache, if allowed
       if [ "$DYNDNS_OLD_CACHE_FALLBACK" = "1" ]; then
@@ -110,7 +128,7 @@ dyndns_host_to_cache()
         echo "$host " >>"$DYNDNS_HOST_CACHE".new
         return $retval
       else
-        echo "** ERROR($retval): Unresolvable host \"$host\". Re-using old IP ($host_ip)! **" >&2 
+        echo "** WARNING($retval): Unresolvable host \"$host\". Re-using old IP ($host_ip)! **" >&2 
       fi
     fi
     echo "$host_ip"
