fixed: traffic-accounting-helper duplicated entries of multi-IP hosts and ignored new hosts
- Each run combined every log entry of a host with every current IP, so the
  entries (and totals) of hosts with multiple IPs doubled on every run
- A host (or IP) without an entry yet, eg. a newly added host or an empty log,
  was never monitored
- Each current IP now uses its own entry, or else one of an IP the host no
  longer has (eg. dynamic DNS), and starts at zero without one
- When resolving a host fails, its entries are kept instead of dropped

diff --git a/share/arno-iptables-firewall/plugins/traffic-accounting-helper b/share/arno-iptables-firewall/plugins/traffic-accounting-helper
--- a/share/arno-iptables-firewall/plugins/traffic-accounting-helper
+++ b/share/arno-iptables-firewall/plugins/traffic-accounting-helper
@@ -39,7 +39,7 @@ traffic_accounting_helper_sanity_check()
 
 traffic_accounting_helper_do_work()
 {
-  local RETVAL=0
+  local RETVAL=0 used_ips entry old_entry
 
   # Touch the log file (just in case it doesn't exist yet):
   touch /var/log/traffic-accounting.log
@@ -63,12 +63,39 @@ traffic_accounting_helper_do_work()
   for host in $TRAFFIC_ACCOUNTING_HOSTS $DEFAULT_ADDR; do
     old_entries="$(grep "^$host " /var/log/traffic-accounting.log)"
 
-    # Process all entries for host
-    IFS=$EOL
-    for old_entry in $old_entries; do
+    # Get host_ip, if it fails, skip rule (but keep its entries)
+    # Parse/get hostname. Try to use host cache if applicable
+    # NOTE: get_dynamic_host_cached returns hostname in $host_ip
+    if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
+      echo "** WARNING: Skipping rule for \"$host\"! **" >&2
+      if [ -n "$old_entries" ]; then
+        echo "$old_entries" >>/tmp/traffic-accounting.new
+      fi
+      RETVAL=1
+      continue
+    fi
+
+    # Process all (current) IPs of the host
+    used_ips=" "
+    IFS=' ,'
+    for mon_host_ip in $host_ip; do
+      # Use the entry of this IP, else one of an IP the host no longer has (eg.
+      # with dynamic DNS). A new host (or IP) has no entry and starts at zero
+      old_entry="$(echo "$old_entries" |grep "^$host $mon_host_ip " |head -n1)"
+      if [ -z "$old_entry" ]; then
+        IFS=$EOL
+        for entry in $old_entries; do
+          case " $(echo "$host_ip" |tr ',' ' ')$used_ips" in
+            *" $(echo "$entry" |cut -s -d' ' -f2) "*) ;;
+            *) old_entry="$entry"; break ;;
+          esac
+        done
+      fi
+
       old_ip="$(echo "$old_entry" |cut -s -d' ' -f2)"
       old_in_value="$(echo "$old_entry" |cut -s -d' ' -f3)"
       old_out_value="$(echo "$old_entry" |cut -s -d' ' -f4)"
+      used_ips="$used_ips$old_ip "
 
       # If value is non-existant make it zero
       if [ -z "$old_in_value" ]; then
@@ -80,37 +107,46 @@ traffic_accounting_helper_do_work()
         old_out_value=0
       fi
 
-      # Get host_ip, if it fails, skip rule
-      # Parse/get hostname. Try to use host cache if applicable
-      # NOTE: get_dynamic_host_cached returns hostname in $host_ip
-      if ! get_dynamic_host_cached $host || [ -z "$host_ip" ]; then
-        echo "** WARNING: Skipping rule for \"$host\"! **" >&2
-        RETVAL=1
-        continue
+      echo "${INDENT}Monitoring host \"$host\" with IP: $mon_host_ip"
+
+      if [ "$VERBOSE" = "1" ]; then
+        printf "${INDENT}old_ip=$old_ip host_ip=$mon_host_ip "
       fi
 
-      IFS=' ,'
-      for mon_host_ip in $host_ip; do
-        echo "${INDENT}Monitoring host \"$host\" with IP: $mon_host_ip"
+      # Process input chain
+      OLDFOUND=0
+      if [ -n "$old_ip" ]; then
+        get_numeric_ip_version "$mon_host_ip"
+        case $? in
+        4)
+          LCOUNT=0
+          IFS=$EOL
+          for LINE in `ip4tables -xnvL ACCOUNTING_INPUT_CHAIN |sed -e "1,2d"`; do
+            ipt_ip="$(echo "$LINE" |awk '{ print $8 }')"
 
-        if [ "$VERBOSE" = "1" ]; then
-          printf "${INDENT}old_ip=$old_ip host_ip=$mon_host_ip "
-        fi
+            LCOUNT=$((LCOUNT + 1))
+            if [ "$ipt_ip" = "$old_ip" ]; then
+              ip4tables -R ACCOUNTING_INPUT_CHAIN $LCOUNT -s $mon_host_ip -j RETURN
+              if [ "$VERBOSE" = "1" ]; then
+                printf "in_action=update "
+              fi
+              OLDFOUND=1
+              ipt_in_value="$(echo "$LINE" |awk '{ print $2 }')"
 
-        # Process input chain
-        OLDFOUND=0
-        if [ -n "$old_ip" ]; then
-          get_numeric_ip_version "$mon_host_ip"
-          case $? in
-          4)
+              break
+            fi
+          done
+          ;;
+        6)
+          if [ "$IPV6_SUPPORT" = "1" ]; then
             LCOUNT=0
             IFS=$EOL
-            for LINE in `ip4tables -xnvL ACCOUNTING_INPUT_CHAIN |sed -e "1,2d"`; do
-              ipt_ip="$(echo "$LINE" |awk '{ print $8 }')"
+            for LINE in `ip6tables -xnvL ACCOUNTING_INPUT_CHAIN |sed -e "1,2d"`; do
+              ipt_ip="$(echo "$LINE" |awk '{ print $7 }')"
 
               LCOUNT=$((LCOUNT + 1))
               if [ "$ipt_ip" = "$old_ip" ]; then
-                ip4tables -R ACCOUNTING_INPUT_CHAIN $LCOUNT -s $mon_host_ip -j RETURN
+                ip6tables -R ACCOUNTING_INPUT_CHAIN $LCOUNT -s $mon_host_ip -j RETURN
                 if [ "$VERBOSE" = "1" ]; then
                   printf "in_action=update "
                 fi
@@ -120,60 +156,60 @@ traffic_accounting_helper_do_work()
                 break
               fi
             done
-            ;;
-          6)
-            if [ "$IPV6_SUPPORT" = "1" ]; then
-              LCOUNT=0
-              IFS=$EOL
-              for LINE in `ip6tables -xnvL ACCOUNTING_INPUT_CHAIN |sed -e "1,2d"`; do
-                ipt_ip="$(echo "$LINE" |awk '{ print $7 }')"
+          fi
+          ;;
+        esac
+      fi
 
-                LCOUNT=$((LCOUNT + 1))
-                if [ "$ipt_ip" = "$old_ip" ]; then
-                  ip6tables -R ACCOUNTING_INPUT_CHAIN $LCOUNT -s $mon_host_ip -j RETURN
-                  if [ "$VERBOSE" = "1" ]; then
-                    printf "in_action=update "
-                  fi
-                  OLDFOUND=1
-                  ipt_in_value="$(echo "$LINE" |awk '{ print $2 }')"
+      if [ $OLDFOUND -eq 0 ]; then
+        if [ "$VERBOSE" = "1" ]; then
+          printf "in_action=add "
+        fi
 
-                  break
-                fi
-              done
+        if [ "$mon_host_ip" = "0.0.0.0/0" -o "$mon_host_ip" = "::/0" ]; then
+          iptables -A ACCOUNTING_INPUT_CHAIN -s $mon_host_ip -j RETURN
+        else
+          iptables -I ACCOUNTING_INPUT_CHAIN 1 -s $mon_host_ip -j RETURN
+        fi
+
+        # Preset values to zero as none exist yet
+        ipt_in_value=0
+      fi
+
+      # Process output chain
+      OLDFOUND=0
+      if [ -n "$old_ip" ]; then
+        get_numeric_ip_version "$mon_host_ip"
+        case $? in
+        4)
+          LCOUNT=0
+          IFS=$EOL
+          for LINE in `ip4tables -xnvL ACCOUNTING_OUTPUT_CHAIN |sed -e "1,2d"`; do
+            ipt_ip="$(echo "$LINE" |awk '{ print $9 }')"
+
+            LCOUNT=$((LCOUNT + 1))
+            if [ "$ipt_ip" = "$old_ip" ]; then
+              ip4tables -R ACCOUNTING_OUTPUT_CHAIN $LCOUNT -d $mon_host_ip -j RETURN
+              if [ "$VERBOSE" = "1" ]; then
+                printf "out_action=update "
+              fi
+              OLDFOUND=1
+              ipt_out_value="$(echo "$LINE" |awk '{ print $2 }')"
+
+              break
             fi
-            ;;
-          esac
-        fi
-
-        if [ $OLDFOUND -eq 0 ]; then
-          if [ "$VERBOSE" = "1" ]; then
-            printf "in_action=add "
-          fi
-
-          if [ "$mon_host_ip" = "0.0.0.0/0" -o "$mon_host_ip" = "::/0" ]; then
-            iptables -A ACCOUNTING_INPUT_CHAIN -s $mon_host_ip -j RETURN
-          else
-            iptables -I ACCOUNTING_INPUT_CHAIN 1 -s $mon_host_ip -j RETURN
-          fi
-
-          # Preset values to zero as none exist yet
-          ipt_in_value=0
-        fi
-
-        # Process output chain
-        OLDFOUND=0
-        if [ -n "$old_ip" ]; then
-          get_numeric_ip_version "$mon_host_ip"
-          case $? in
-          4)
+          done
+          ;;
+        6)
+          if [ "$IPV6_SUPPORT" = "1" ]; then
             LCOUNT=0
             IFS=$EOL
-            for LINE in `ip4tables -xnvL ACCOUNTING_OUTPUT_CHAIN |sed -e "1,2d"`; do
-              ipt_ip="$(echo "$LINE" |awk '{ print $9 }')"
+            for LINE in `ip6tables -xnvL ACCOUNTING_OUTPUT_CHAIN |sed -e "1,2d"`; do
+              ipt_ip="$(echo "$LINE" |awk '{ print $8 }')"
 
               LCOUNT=$((LCOUNT + 1))
               if [ "$ipt_ip" = "$old_ip" ]; then
-                ip4tables -R ACCOUNTING_OUTPUT_CHAIN $LCOUNT -d $mon_host_ip -j RETURN
+                ip6tables -R ACCOUNTING_OUTPUT_CHAIN $LCOUNT -d $mon_host_ip -j RETURN
                 if [ "$VERBOSE" = "1" ]; then
                   printf "out_action=update "
                 fi
@@ -183,62 +219,41 @@ traffic_accounting_helper_do_work()
                 break
               fi
             done
-            ;;
-          6)
-            if [ "$IPV6_SUPPORT" = "1" ]; then
-              LCOUNT=0
-              IFS=$EOL
-              for LINE in `ip6tables -xnvL ACCOUNTING_OUTPUT_CHAIN |sed -e "1,2d"`; do
-                ipt_ip="$(echo "$LINE" |awk '{ print $8 }')"
-
-                LCOUNT=$((LCOUNT + 1))
-                if [ "$ipt_ip" = "$old_ip" ]; then
-                  ip6tables -R ACCOUNTING_OUTPUT_CHAIN $LCOUNT -d $mon_host_ip -j RETURN
-                  if [ "$VERBOSE" = "1" ]; then
-                    printf "out_action=update "
-                  fi
-                  OLDFOUND=1
-                  ipt_out_value="$(echo "$LINE" |awk '{ print $2 }')"
-
-                  break
-                fi
-              done
-            fi
-            ;;
-          esac
-        fi
-
-        if [ $OLDFOUND -eq 0 ]; then
-          if [ "$VERBOSE" = "1" ]; then
-            printf "out_action=add "
           fi
+          ;;
+        esac
+      fi
 
-          if [ "$mon_host_ip" = "0.0.0.0/0" -o "$mon_host_ip" = "::/0" ]; then
-            iptables -A ACCOUNTING_OUTPUT_CHAIN -d $mon_host_ip -j RETURN
-          else
-            iptables -I ACCOUNTING_OUTPUT_CHAIN 1 -d $mon_host_ip -j RETURN
-          fi
-
-          # Preset values to zero as none exist yet
-          ipt_out_value=0
-        fi
-
-        # Calculate new in value
-        new_in_value=$((old_in_value + ipt_in_value))
-
-        # Calculate new out value
-        new_out_value=$((old_out_value + ipt_out_value))
+      if [ $OLDFOUND -eq 0 ]; then
         if [ "$VERBOSE" = "1" ]; then
-          printf "old_in_val=$old_in_value ipt_in_val=$ipt_in_value new_in_val=$new_in_value old_out_val=$old_out_value ipt_out_val=$ipt_out_value new_out_val=$new_out_value"
+          printf "out_action=add "
         fi
 
-        # Create entry in accounting file
-        echo "$host $mon_host_ip $new_in_value $new_out_value" >>/tmp/traffic-accounting.new
-
-        if [ "$VERBOSE" = "1" ]; then
-          printf "\n\n"
+        if [ "$mon_host_ip" = "0.0.0.0/0" -o "$mon_host_ip" = "::/0" ]; then
+          iptables -A ACCOUNTING_OUTPUT_CHAIN -d $mon_host_ip -j RETURN
+        else
+          iptables -I ACCOUNTING_OUTPUT_CHAIN 1 -d $mon_host_ip -j RETURN
         fi
-      done
+
+        # Preset values to zero as none exist yet
+        ipt_out_value=0
+      fi
+
+      # Calculate new in value
+      new_in_value=$((old_in_value + ipt_in_value))
+
+      # Calculate new out value
+      new_out_value=$((old_out_value + ipt_out_value))
+      if [ "$VERBOSE" = "1" ]; then
+        printf "old_in_val=$old_in_value ipt_in_val=$ipt_in_value new_in_val=$new_in_value old_out_val=$old_out_value ipt_out_val=$ipt_out_value new_out_val=$new_out_value"
+      fi
+
+      # Create entry in accounting file
+      echo "$host $mon_host_ip $new_in_value $new_out_value" >>/tmp/traffic-accounting.new
+
+      if [ "$VERBOSE" = "1" ]; then
+        printf "\n\n"
+      fi
     done
   done
 
