changed: Allow not specifying ports for webfilter/output policy

diff --git a/share/arno-iptables-firewall/plugins/webfilter-helper b/share/arno-iptables-firewall/plugins/webfilter-helper
--- a/share/arno-iptables-firewall/plugins/webfilter-helper
+++ b/share/arno-iptables-firewall/plugins/webfilter-helper
@@ -8,6 +8,14 @@ PLUGIN_RET_VAL=0
 # Check sanity of environment
 webfilter_helper_sanity_check()
 {
+  if [ -z "$WEBFILTER_HOST_OPEN_TCP" -a -z "$WEBFILTER_HOST_OPEN_UDP" -a \
+       -z "$WEBFILTER_HOST_OPEN_IP"  -a -z "$WEBFILTER_HOST_OPEN_ICMP" -a \
+       -z "$WEBFILTER_HOST_DENY_TCP" -a -z "$WEBFILTER_HOST_DENY_UDP" -a \
+       -z "$WEBFILTER_HOST_DENY_IP"  -a -z "$WEBFILTER_HOST_DENY_ICMP" ]; then
+    echo "** ERROR: The plugin config file is not (properly) setup!" >&2
+    return 1
+  fi
+
   # Check whether chain exists
   if ! ip4tables -nL WEBFILTER_ACL >/dev/null 2>&1; then
     echo "** ERROR: WEBFILTER_ACL does not exist! **" >&2
@@ -25,13 +33,18 @@ webfilter_helper_do_work()
   # Flush the WEBFILTER_ACL
   iptables -F WEBFILTER_ACL
 
+  # Fallback to DROP-policy in case it's not (properly) specified
+  if [ "$WEBFILTER_DENY_POLICY" != "REJECT" ]; then
+    WEBFILTER_DENY_POLICY="DROP"
+  fi
+
   unset IFS
   for rule in $WEBFILTER_HOST_DENY_TCP; do
-    if parse_rule "$rule" WEBFILTER_HOST_DENY_TCP "interfaces-shosts-dhosts-ports:ANYPORT"; then
-      echo "${INDENT}Denying access from $shosts to $dhosts for TCP port(s): $ports"
+    if parse_rule "$rule" WEBFILTER_HOST_DENY_TCP "interfaces-srcips-hosts-ports:ANYPORT"; then
+      echo "${INDENT}$(show_if_ip "$interfaces" "$srcips")Denying $hosts for TCP port(s): $ports"
 
       IFS=' ,'
-      for dhost in `ip_range "$dhosts"`; do
+      for dhost in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $dhost || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping TCP deny rule(s) for unresolvable host \"$dhost\"! **" >&2
           RETVAL=1
@@ -39,14 +52,16 @@ webfilter_helper_do_work()
         fi
 
         for dhost_ip in $host_ip; do
-          for shost_ip in `ip_range "$shosts"`; do
-            for port in $ports; do
-              if [ "$WEBFILTER_DENY_LOG" = "1" ]; then
-                iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p tcp --dport $port -m limit --limit 1/m -j LOG \
-                  --log-level $LOGLEVEL --log-prefix "AIF:Webfilter denied: "
-              fi
+          for port in $ports; do
+            for interface in $interfaces; do
+              for srcip in $srcips; do
+                if [ "$WEBFILTER_DENY_LOG" = "1" ]; then
+                  iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p tcp --dport $port -m limit --limit 1/m -j LOG \
+                    --log-level $LOGLEVEL --log-prefix "AIF:Webfilter denied: "
+                fi
 
-              iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p tcp --dport $port -j $WEBFILTER_DENY_POLICY
+                iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p tcp --dport $port -j $WEBFILTER_DENY_POLICY
+              done
             done
           done
         done
@@ -56,11 +71,11 @@ webfilter_helper_do_work()
 
   unset IFS
   for rule in $WEBFILTER_HOST_DENY_UDP; do
-    if parse_rule "$rule" WEBFILTER_HOST_DENY_UDP "interfaces-shosts-dhosts-ports:ANYPORT"; then
-      echo "${INDENT}Denying access from $shosts to $dhosts for UDP port(s): $ports"
+    if parse_rule "$rule" WEBFILTER_HOST_DENY_UDP "interfaces-srcips-hosts-ports:ANYPORT"; then
+      echo "${INDENT}$(show_if_ip "$interfaces" "$srcips")Denying $hosts for UDP port(s): $ports"
 
       IFS=' ,'
-      for dhost in `ip_range "$dhosts"`; do
+      for dhost in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $dhost || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping UDP deny rule(s) for unresolvable host \"$dhost\"! **" >&2
           RETVAL=1
@@ -68,14 +83,16 @@ webfilter_helper_do_work()
         fi
 
         for dhost_ip in $host_ip; do
-          for shost_ip in `ip_range "$shosts"`; do
-            for port in $ports; do
-              if [ "$WEBFILTER_DENY_LOG" = "1" ]; then
-                iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p udp --dport $port -m limit --limit 1/m -j LOG \
-                  --log-level $LOGLEVEL --log-prefix "AIF:Webfilter denied: "
-              fi
+          for port in $ports; do
+            for interface in $interfaces; do
+              for srcip in $srcips; do
+                if [ "$WEBFILTER_DENY_LOG" = "1" ]; then
+                  iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p udp --dport $port -m limit --limit 1/m -j LOG \
+                    --log-level $LOGLEVEL --log-prefix "AIF:Webfilter denied: "
+                fi
 
-              iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p udp --dport $port -j $WEBFILTER_DENY_POLICY
+                iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p udp --dport $port -j $WEBFILTER_DENY_POLICY
+              done
             done
           done
         done
@@ -85,11 +102,11 @@ webfilter_helper_do_work()
 
   unset IFS
   for rule in $WEBFILTER_HOST_DENY_ICMP; do
-    if parse_rule "$rule" WEBFILTER_HOST_DENY_ICMP "shosts:ANYHOST-dhosts"; then
-      echo "${INDENT}Denying access from $shosts to $dhosts for ICMP requests"
+    if parse_rule "$rule" WEBFILTER_HOST_DENY_ICMP "interfaces-srcips-hosts"; then
+      echo "${INDENT}$(show_if_ip "$interfaces" "$srcips")Denying $hosts for ICMP requests"
 
       IFS=' ,'
-      for dhost in `ip_range "$dhosts"`; do
+      for dhost in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $dhost || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping ICMP deny rule(s) for unresolvable host \"$dhost\"! **" >&2
           RETVAL=1
@@ -97,13 +114,14 @@ webfilter_helper_do_work()
         fi
 
         for dhost_ip in $host_ip; do
-          for shost_ip in `ip_range "$shosts"`; do
-            if [ "$WEBFILTER_DENY_LOG" = "1" ]; then
-              iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p icmp --icmp-type echo-request -m limit --limit 1/m -j LOG \
-                --log-level $LOGLEVEL --log-prefix "AIF:Webfilter denied: "
-            fi
+          for interface in $interfaces; do
+            for srcip in $srcips; do
+              if [ "$WEBFILTER_DENY_LOG" = "1" ]; then
+                iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p icmp --icmp-type echo-request -m limit --limit 1/m -j LOG \
+                  --log-level $LOGLEVEL --log-prefix "AIF:Webfilter denied: "
+              fi
 
-            iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p icmp --icmp-type echo-request -j $WEBFILTER_DENY_POLICY
+              iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p icmp --icmp-type echo-request -j $WEBFILTER_DENY_POLICY
           done
         done
       done
@@ -112,11 +130,11 @@ webfilter_helper_do_work()
 
   unset IFS
   for rule in $WEBFILTER_HOST_DENY_IP; do
-    if parse_rule "$rule" WEBFILTER_HOST_DENY_IP "shosts:ANYHOST-dhosts-protos"; then
-      echo "${INDENT}Denying access from $shosts to $dhosts for IP protocol(s): $protos"
+    if parse_rule "$rule" WEBFILTER_HOST_DENY_IP "interfaces-srcips-hosts-protos"; then
+      echo "${INDENT}$(show_if_ip "$interfaces" "$srcips")Denying $hosts for IP protocol(s): $protos"
 
       IFS=' ,'
-      for dhost in `ip_range "$dhosts"`; do
+      for dhost in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $dhost || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping IP deny rule(s) for unresolvable host \"$dhost\"! **" >&2
           RETVAL=1
@@ -124,14 +142,16 @@ webfilter_helper_do_work()
         fi
 
         for dhost_ip in $host_ip; do
-          for shost_ip in `ip_range "$shosts"`; do
-            for proto in $protos; do
-              if [ "$WEBFILTER_DENY_LOG" = "1" ]; then
-                iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p $proto -m limit --limit 1/m -j LOG \
-                  --log-level $LOGLEVEL --log-prefix "AIF:Webfilter denied: "
-              fi
+          for proto in $protos; do
+            for interface in $interfaces; do
+              for srcip in $srcips; do
+                if [ "$WEBFILTER_DENY_LOG" = "1" ]; then
+                  iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p $proto -m limit --limit 1/m -j LOG \
+                    --log-level $LOGLEVEL --log-prefix "AIF:Webfilter denied: "
+                fi
 
-              iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p $proto -j $WEBFILTER_DENY_POLICY
+                iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p $proto -j $WEBFILTER_DENY_POLICY
+              done
             done
           done
         done
@@ -141,11 +161,11 @@ webfilter_helper_do_work()
 
   unset IFS
   for rule in $WEBFILTER_HOST_OPEN_TCP; do
-    if parse_rule "$rule" WEBFILTER_HOST_OPEN_TCP "shosts:ANYHOST-dhosts-ports"; then
-      echo "${INDENT}Allowing access from $shosts to $dhosts for TCP port(s): $ports"
+    if parse_rule "$rule" WEBFILTER_HOST_OPEN_TCP "interfaces-srcips-hosts-ports:ANYPORT"; then
+      echo "${INDENT}$(show_if_ip "$interfaces" "$srcips")Allowing $hosts for TCP port(s): $ports"
 
       IFS=' ,'
-      for dhost in `ip_range "$dhosts"`; do
+      for dhost in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $dhost || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping TCP allow rule(s) for unresolvable host \"$dhost\"! **" >&2
           RETVAL=1
@@ -153,9 +173,11 @@ webfilter_helper_do_work()
         fi
 
         for dhost_ip in $host_ip; do
-          for shost_ip in `ip_range "$shosts"`; do
-            for port in $ports; do
-              iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p tcp --dport $port -j ACCEPT
+          for port in $ports; do
+            for interface in $interfaces; do
+              for srcip in $srcips; do
+                iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p tcp --dport $port -j ACCEPT
+              done
             done
           done
         done
@@ -165,11 +187,11 @@ webfilter_helper_do_work()
 
   unset IFS
   for rule in $WEBFILTER_HOST_OPEN_UDP; do
-    if parse_rule "$rule" WEBFILTER_HOST_OPEN_UDP "shosts:ANYHOST-dhosts-ports"; then
-      echo "${INDENT}Allowing access from $shosts to $dhosts for UDP port(s): $ports"
+    if parse_rule "$rule" WEBFILTER_HOST_OPEN_UDP "interfaces-srcips-hosts-ports:ANYPORT"; then
+      echo "${INDENT}$(show_if_ip "$interfaces" "$srcips")Allowing $hosts for UDP port(s): $ports"
 
       IFS=' ,'
-      for dhost in `ip_range "$dhosts"`; do
+      for dhost in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $dhost || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping UDP allow rule(s) for unresolvable host \"$dhost\"! **" >&2
           RETVAL=1
@@ -177,9 +199,11 @@ webfilter_helper_do_work()
         fi
 
         for dhost_ip in $host_ip; do
-          for shost_ip in `ip_range "$shosts"`; do
-            for port in $ports; do
-              iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p udp --dport $port -j ACCEPT
+          for port in $ports; do
+            for interface in $interfaces; do
+              for srcip in $srcips; do
+                iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p udp --dport $port -j ACCEPT
+              done
             done
           done
         done
@@ -190,11 +214,11 @@ webfilter_helper_do_work()
   unset IFS
 
   for rule in $WEBFILTER_HOST_OPEN_ICMP; do
-    if parse_rule "$rule" WEBFILTER_HOST_OPEN_ICMP "shosts:ANYHOST-dhosts"; then
-      echo "${INDENT}Allowing access from $shosts to $dhosts for ICMP requests"
+    if parse_rule "$rule" WEBFILTER_HOST_OPEN_ICMP "interfaces-srcips-hosts"; then
+      echo "${INDENT}$(show_if_ip "$interfaces" "$srcips")Allowing $hosts for ICMP requests"
 
       IFS=' ,'
-      for dhost in `ip_range "$dhosts"`; do
+      for dhost in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $dhost || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping ICMP allow rule(s) for unresolvable host \"$dhost\"! **" >&2
           RETVAL=1
@@ -202,8 +226,10 @@ webfilter_helper_do_work()
         fi
 
         for dhost_ip in $host_ip; do
-          for shost_ip in $shosts; do
-            iptables -A WEBFILTER_ACL -s $shost_ip -d $dhost_ip -p icmp --icmp-type echo-request -j ACCEPT
+          for interface in $interfaces; do
+            for srcip in $srcips; do
+              iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p icmp --icmp-type echo-request -j ACCEPT
+            done
           done
         done
       done
@@ -212,11 +238,11 @@ webfilter_helper_do_work()
 
   unset IFS
   for rule in $WEBFILTER_HOST_OPEN_IP; do
-    if parse_rule "$rule" WEBFILTER_HOST_OPEN_IP "shosts:ANYHOST-dhosts-protos"; then
-      echo "${INDENT}Allowing access from $shosts to $dhosts for IP protocol(s): $protos"
+    if parse_rule "$rule" WEBFILTER_HOST_OPEN_IP "interfaces-srcips-hosts-protos"; then
+      echo "${INDENT}$(show_if_ip "$interfaces" "$srcips")Allowing $hosts for IP protocol(s): $protos"
 
       IFS=' ,'
-      for dhost in `ip_range "$dhosts"`; do
+      for dhost in `ip_range "$hosts"`; do
         if ! get_dynamic_host_cached $dhost || [ -z "$host_ip" ]; then
           echo "** WARNING: Skipping IP allow rule(s) for unresolvable host \"$dhost\"! **" >&2
           RETVAL=1
@@ -224,9 +250,11 @@ webfilter_helper_do_work()
         fi
 
         for dhost_ip in $host_ip; do
-          for shost_ip in $shosts; do
-            for proto in $protos; do
-              iptables -A WEBFILTER_ACL -d $dhost_ip -p $proto -j ACCEPT
+          for proto in $protos; do
+            for interface in $interfaces; do
+              for srcip in $srcips; do
+                iptables -A WEBFILTER_ACL $(ipt_if -o "$interface") -s $srcip -d $dhost_ip -p $proto -j ACCEPT
+              done
             done
           done
         done
